// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6GJVM0H6se3PDj15At2FRo7GwJl-bVD4',
    appId: '1:845446533729:web:c766ecd77ce0b0f5535020',
    messagingSenderId: '845446533729',
    projectId: 'note-app-ce183',
    authDomain: 'note-app-ce183.firebaseapp.com',
    storageBucket: 'note-app-ce183.firebasestorage.app',
    measurementId: 'G-CFMPQGJMK8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS6fIN_yiVD0gAp9yocSNP4lvtemPh2Ws',
    appId: '1:845446533729:android:2f7db71b5a6d270c535020',
    messagingSenderId: '845446533729',
    projectId: 'note-app-ce183',
    storageBucket: 'note-app-ce183.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS2sVTAt8Riiw7xmG57R_uD3cFQirt6AQ',
    appId: '1:845446533729:ios:bf12cf6acd8ec1a1535020',
    messagingSenderId: '845446533729',
    projectId: 'note-app-ce183',
    storageBucket: 'note-app-ce183.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS2sVTAt8Riiw7xmG57R_uD3cFQirt6AQ',
    appId: '1:845446533729:ios:bf12cf6acd8ec1a1535020',
    messagingSenderId: '845446533729',
    projectId: 'note-app-ce183',
    storageBucket: 'note-app-ce183.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6GJVM0H6se3PDj15At2FRo7GwJl-bVD4',
    appId: '1:845446533729:web:83333f4d769d9816535020',
    messagingSenderId: '845446533729',
    projectId: 'note-app-ce183',
    authDomain: 'note-app-ce183.firebaseapp.com',
    storageBucket: 'note-app-ce183.firebasestorage.app',
    measurementId: 'G-CG1ELR1K0F',
  );
}
